/**
 * Contexto compartido por paginas lazy-loaded (Tableros, Inventario, Dashboard, etc.).
 * Generado desde App.jsx � mantener sincronizado al agregar props al contexto.
 */
export function buildPaginasContexto(d) {
  return {
    ACTION_DEFINITIONS: d.ACTION_DEFINITIONS,
    BOOTSTRAP_MASTER_ID: d.BOOTSTRAP_MASTER_ID,
    AlertTriangle: d.AlertTriangle,
    activeAssignableUsers: d.activeAssignableUsers,
    activeWeek: d.activeWeek,
    actionPermissions: d.actionPermissions,
    adminReportRows: d.adminReportRows,
    adminTab: d.adminTab,
    applyPermissionPreset: d.applyPermissionPreset,
    applyRemoteWarehouseState: d.applyRemoteWarehouseState,
    ArrowUp: d.ArrowUp,
    auditFilters: d.auditFilters,
    BarChart3: d.BarChart3,
    boardAssignmentsByUser: d.boardAssignmentsByUser,
    boardRuntimeFeedback: d.boardRuntimeFeedback,
    buildSelectOptions: d.buildSelectOptions,
    CalendarDays: d.CalendarDays,
    canDoBoardAction: d.canDoBoardAction,
    canEditBoard: d.canEditBoard,
    canEditBoardRowRecord: d.canEditBoardRowRecord,
    canOperateBoardRowRecord: d.canOperateBoardRowRecord,
    catalogMap: d.catalogMap,
    catalogWeekGroups: d.catalogWeekGroups,
    changeBoardRowStatus: d.changeBoardRowStatus,
    CircleCheckBig: d.CircleCheckBig,
    ClipboardList: d.ClipboardList,
    Clock3: d.Clock3,
    Copy: d.Copy,
    creatableRoles: d.creatableRoles,
    createBoardRow: d.createBoardRow,
    boardRowCreationPending: d.boardRowCreationPending,
    currentInventoryDeletePermission: d.currentInventoryDeletePermission,
    currentInventoryImportPermission: d.currentInventoryImportPermission,
    currentInventoryItems: d.currentInventoryItems,
    currentInventoryManagePermission: d.currentInventoryManagePermission,
    currentInventoryMovements: d.currentInventoryMovements,
    currentUser: d.currentUser,
    activeAreaScopes: d.activeAreaScopes,
    customBoardActionsMenuOpen: d.customBoardActionsMenuOpen,
    customBoardActionsMenuRef: d.customBoardActionsMenuRef,
    customBoardMetrics: d.customBoardMetrics,
    customBoardSearch: d.customBoardSearch,
    dashboardActivityRows: d.dashboardActivityRows,
    dashboardAreaRows: d.dashboardAreaRows,
    dashboardCatalogFrequencyRows: d.dashboardCatalogFrequencyRows,
    dashboardCatalogTypeRows: d.dashboardCatalogTypeRows,
    dashboardDynamicMetricRows: d.dashboardDynamicMetricRows,
    dashboardAreaBoardDetailedRows: d.dashboardAreaBoardDetailedRows,
    dashboardInventoryProductTimeRows: d.dashboardInventoryProductTimeRows,
    dashboardPalletLeaderboardRows: d.dashboardPalletLeaderboardRows,
    dashboardProductPerformanceRows: d.dashboardProductPerformanceRows,
    dashboardProductAggregateRows: d.dashboardProductAggregateRows,
    dashboardBoardInsightRows: d.dashboardBoardInsightRows,
    dashboardBoardKpiCards: d.dashboardBoardKpiCards,
    dashboardDistributionRows: d.dashboardDistributionRows,
    dashboardFilters: d.dashboardFilters,
    filteredDashboardRecords: d.filteredDashboardRecords,
    dateFilteredDashboardRecords: d.dateFilteredDashboardRecords,
    areaNavSections: d.areaNavSections,
    dynamicAreaSectionRoots: d.dynamicAreaSectionRoots,
    transportRecords: d.transportRecords,
    dashboardVisibleControlBoards: d.dashboardVisibleControlBoards,
    dashboardIshikawaRows: d.dashboardIshikawaRows,
    dashboardMetrics: d.dashboardMetrics,
    dashboardParetoRows: d.dashboardParetoRows,
    dashboardPeriodOptions: d.dashboardPeriodOptions,
    dashboardResponsibleRows: d.dashboardResponsibleRows,
    dashboardSectionsOpen: d.dashboardSectionsOpen,
    dashboardTrendRows: d.dashboardTrendRows,
    DashboardBarRow: d.DashboardBarRow,
    DashboardCauseCard: d.DashboardCauseCard,
    DashboardColumnChart: d.DashboardColumnChart,
    DashboardLineChart: d.DashboardLineChart,
    DashboardIshikawaDiagram: d.DashboardIshikawaDiagram,
    DashboardKpiCard: d.DashboardKpiCard,
    DashboardKpiBento: d.DashboardKpiBento,
    DashboardParetoChart: d.DashboardParetoChart,
    DashboardParetoRow: d.DashboardParetoRow,
    DashboardPieChart: d.DashboardPieChart,
    DashboardProgressMetric: d.DashboardProgressMetric,
    DashboardRankItem: d.DashboardRankItem,
    DashboardSection: d.DashboardSection,
    departmentOptions: d.departmentOptions,
    downloadInventoryTemplate: d.downloadInventoryTemplate,
    exportMaintenanceInventoryItemsToCsv: d.exportMaintenanceInventoryItemsToCsv,
    maintenanceInventoryItems: d.maintenanceInventoryItems,
    submitMaintenanceUsage: d.submitMaintenanceUsage,
    Download: d.Download,
    duplicateBoardRecord: d.duplicateBoardRecord,
    Eye: d.Eye,
    editableVisibleBoards: d.editableVisibleBoards,
    exportPermissionRules: d.exportPermissionRules,
    exportSelectedBoardToExcel: d.exportSelectedBoardToExcel,
    previewSelectedBoardPdf: d.previewSelectedBoardPdf,
    exportSelectedBoardToPdf: d.exportSelectedBoardToPdf,
    filteredAuditLog: d.filteredAuditLog,
    filteredBoardTemplates: d.filteredBoardTemplates,
    filteredUsers: d.filteredUsers,
    filteredVisibleControlBoards: d.filteredVisibleControlBoards,
    formatDate: d.formatDate,
    formatDateTime: d.formatDateTime,
    formatDurationClock: d.formatDurationClock,
    formatMetricNumber: d.formatMetricNumber,
    formatMinutes: d.formatMinutes,
    formatPercent: d.formatPercent,
    formatTime: d.formatTime,
    Gauge: d.Gauge,
    getActivityLabel: d.getActivityLabel,
    getActivityFrequencyLabel: d.getActivityFrequencyLabel,
    getBoardAssignmentSummary: d.getBoardAssignmentSummary,
    getBoardFieldCellStyle: d.getBoardFieldCellStyle,
    getOrderedBoardColumns: d.getOrderedBoardColumns,
    getBoardFieldValue: d.getBoardFieldValue,
    renderBoardFieldLabel: d.renderBoardFieldLabel,
    getDashboardPeriodTypeLabel: d.getDashboardPeriodTypeLabel,
    getElapsedSeconds: d.getElapsedSeconds,
    getFieldColorRule: d.getFieldColorRule,
    getResponsibleVisual: d.getResponsibleVisual,
    getRoleBadgeClass: d.getRoleBadgeClass,
    getTimeLimitMinutes: d.getTimeLimitMinutes,
    getUserArea: d.getUserArea,
    getUserJobTitle: d.getUserJobTitle,
    handleInventoryImport: d.handleInventoryImport,
    handlePermissionImport: d.handlePermissionImport,
    historyWeek: d.historyWeek,
    inventoryActionsMenuOpen: d.inventoryActionsMenuOpen,
    inventoryActionsMenuRef: d.inventoryActionsMenuRef,
    inventoryFileInputRef: d.inventoryFileInputRef,
    inventoryImportFeedback: d.inventoryImportFeedback,
    inventoryLinkedCleaningRows: d.inventoryLinkedCleaningRows,
    inventoryMovementSavedDestinations: d.inventoryMovementSavedDestinations,
    inventoryMovementSavedLocations: d.inventoryMovementSavedLocations,
    state: d.state,
    setState: d.setState,
    setLoginDirectory: d.setLoginDirectory,
    skipNextSyncRef: d.skipNextSyncRef,
    setSyncStatus: d.setSyncStatus,
    transportState: d.state.transport || { config: [], activeDateKey: "", activeRecords: [], historyRecords: [] },
    users: Array.isArray(d.state.users) ? d.state.users : [],
    createTransportRecord: d.createTransportRecord,
    updateTransportRecord: d.updateTransportRecord,
    canManageTransport: Boolean(d.actionPermissions?.manageTransport),
    navTransportSection: d.navTransportSection,
    setNavTransportSection: d.setNavTransportSection,
    navTransportTab: d.navTransportTab,
    setNavTransportTab: d.setNavTransportTab,
    auditShortcutPreset: d.auditShortcutPreset,
    setAuditShortcutPreset: d.setAuditShortcutPreset,
    onAuditTabChange: d.onAuditTabChange,
    documentacionState: d.state.documentacion || { records: [], customAreas: [] },
    createDocumentacionRecord: d.createDocumentacionRecord,
    updateDocumentacionRecord: d.updateDocumentacionRecord,
    addDocumentacionArea: d.addDocumentacionArea,
    deleteDocumentacionArea: d.deleteDocumentacionArea,
    currentInventorySupplyableCount: d.currentInventorySupplyableItems?.length ?? 0,
    inventoryCleaningSite: d.inventoryCleaningSite,
    inventoryDestinationWarehouse: d.inventoryDestinationWarehouse,
    setInventoryDestinationWarehouse: d.setInventoryDestinationWarehouse,
    inventorySearch: d.inventorySearch,
    inventoryStats: d.inventoryStats,
    inventoryTab: d.inventoryTab,
    inventoryItemsById: d.inventoryItemsById,
    CLEANING_SITE_OPTIONS: d.CLEANING_SITE_OPTIONS,
    openInventoryBulkRestockModal: d.openInventoryBulkRestockModal,
    openInventoryRestockModal: d.openInventoryRestockModal,
    openInventoryTransferHistory: d.openInventoryTransferHistory,
    openInventoryTransferViewer: d.openInventoryTransferViewer,
    openOrderInventoryTransfer: d.openOrderInventoryTransfer,
    openInventoryDestinationModal: d.openInventoryDestinationModal,
    closeInventoryDestinationModal: d.closeInventoryDestinationModal,
    submitInventoryDestinationModal: d.submitInventoryDestinationModal,
    deleteInventoryDestination: d.deleteInventoryDestination,
    inventoryDestinationModal: d.inventoryDestinationModal,
    inventoryTransferAvailableWarehouses: d.inventoryTransferAvailableWarehouses,
    inventoryTransferDestinationsByWarehouse: d.inventoryTransferDestinationsByWarehouse,
    orderInventoryTransferMovements: d.orderInventoryTransferMovements,
    maintenanceInventoryTransferMovements: d.maintenanceInventoryTransferMovements,
    orderInventoryTransferSummary: d.orderInventoryTransferSummary,
    maintenanceInventoryTransferSummary: d.maintenanceInventoryTransferSummary,
    InventoryLookupInput: d.InventoryLookupInput,
    InventoryStockBar: d.InventoryStockBar,
    INVENTORY_DOMAIN_BASE: d.INVENTORY_DOMAIN_BASE,
    INVENTORY_DOMAIN_CLEANING: d.INVENTORY_DOMAIN_CLEANING,
    INVENTORY_DOMAIN_ORDERS: d.INVENTORY_DOMAIN_ORDERS,
    INVENTORY_DOMAIN_MAINTENANCE: d.INVENTORY_DOMAIN_MAINTENANCE,
    INVENTORY_MOVEMENT_CONSUME: d.INVENTORY_MOVEMENT_CONSUME,
    INVENTORY_MOVEMENT_RESTOCK: d.INVENTORY_MOVEMENT_RESTOCK,
    INVENTORY_MOVEMENT_TRANSFER: d.INVENTORY_MOVEMENT_TRANSFER,
    LayoutDashboard: d.LayoutDashboard,
    lowStockInventoryItems: d.lowStockInventoryItems,
    Menu: d.Menu,
    Modal: d.Modal,
    MetricCard: d.MetricCard,
    NAV_ITEMS: d.NAV_ITEMS,
    ACTIVITY_FREQUENCY_OPTIONS: d.ACTIVITY_FREQUENCY_OPTIONS,
    normalizedPermissions: d.normalizedPermissions,
    now: d.now,
    OctagonAlert: d.OctagonAlert,
    openBoardPauseModal: d.openBoardPauseModal,
    openCatalogCreate: d.openCatalogCreate,
    openCatalogEdit: d.openCatalogEdit,
    exportCatalogToCsv: d.exportCatalogToCsv,
    importCatalogFromCsv: d.importCatalogFromCsv,
    openCreateBoardBuilder: d.openCreateBoardBuilder,
    openCreateBoardBuilderFromChecklistTemplate: d.openCreateBoardBuilderFromChecklistTemplate,
    openCreateInventoryItem: d.openCreateInventoryItem,
    openCreateUser: d.openCreateUser,
    openEditBoardBuilder: d.openEditBoardBuilder,
    openEditInventoryItem: d.openEditInventoryItem,
    openEditUser: d.openEditUser,
    openFinishBoardRowConfirm: d.openFinishBoardRowConfirm,
    openInventoryMovement: d.openInventoryMovement,
    deleteArea: async (areaName) => {
      try {
        const result = await d.requestJson(`/warehouse/areas/${encodeURIComponent(areaName)}`, { method: "DELETE" });
        d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      } catch (error) {
        d.pushAppToast(error?.message || "No se pudo eliminar el área.", "danger");
      }
    },
    deleteWeek: async (weekId) => {
      const result = await d.requestJson(`/warehouse/weeks/${weekId}`, { method: "DELETE" });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      return result.data.weekId;
    },
    handleAddAreaOption: d.handleAddAreaOption,
    rootAreaOptions: d.rootAreaOptions,
    splitAreaAndSubArea: d.splitAreaAndSubArea,
    inventoryColumns: Array.isArray(d.state.inventoryColumns) ? d.state.inventoryColumns : [],
    createInventoryColumn: async (payload) => {
      try {
        const result = await d.requestJson("/warehouse/inventory/columns", {
          method: "POST",
          body: JSON.stringify(payload || {}),
        });
        d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
        d.pushAppToast("Columna de inventario creada.", "success");
      } catch (error) {
        d.pushAppToast(error?.message || "No se pudo crear la columna.", "danger");
        throw error;
      }
    },
    deleteInventoryColumn: async (columnId) => {
      try {
        const result = await d.requestJson(`/warehouse/inventory/columns/${columnId}`, { method: "DELETE" });
        d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
        d.pushAppToast("Columna de inventario eliminada.", "success");
      } catch (error) {
        d.pushAppToast(error?.message || "No se pudo eliminar la columna.", "danger");
        throw error;
      }
    },
    inventorySystemColumnSuggestions: d.inventorySystemColumnSuggestions,
    duplicateInventoryItem: async (itemId) => {
      try {
        const result = await d.requestJson(`/warehouse/inventory/${itemId}/duplicate`, { method: "POST" });
        d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
        d.pushAppToast("Artículo duplicado correctamente.", "success");
      } catch (error) {
        d.pushAppToast(error?.message || "No se pudo duplicar el artículo.", "danger");
      }
    },
    processAuditTemplates: Array.isArray(d.state.processAuditTemplates) ? d.state.processAuditTemplates : [],
    processAudits: Array.isArray(d.state.processAudits) ? d.state.processAudits : [],
    processAuditMetrics: d.processAuditMetrics || {},
    upsertProcessAuditTemplate: async (payload) => {
      const result = await d.requestJson("/warehouse/process-audits/templates", {
        method: "POST",
        body: JSON.stringify(payload || {}),
      });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      return result.data.templateId;
    },
    deleteProcessAuditTemplate: async (templateId) => {
      const result = await d.requestJson(`/warehouse/process-audits/templates/${templateId}`, { method: "DELETE" });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
    },
    createProcessAudit: async (payload) => {
      const result = await d.requestJson("/warehouse/process-audits", {
        method: "POST",
        body: JSON.stringify(payload || {}),
      });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      return result.data.auditId;
    },
    updateProcessAudit: async (auditId, payload) => {
      const result = await d.requestJson(`/warehouse/process-audits/${auditId}`, {
        method: "PATCH",
        body: JSON.stringify(payload || {}),
      });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      return result.data.auditId;
    },
    deleteProcessAudit: async (auditId, leadPassword) => {
      const result = await d.requestJson(`/warehouse/process-audits/${auditId}`, {
        method: "DELETE",
        body: JSON.stringify({ leadPassword }),
      });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      return result.data.auditId;
    },
    resetProcessAuditStats: async () => {
      const result = await d.requestJson("/warehouse/process-audits/reset-stats", { method: "POST" });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
    },
    addProcessAuditEvidence: async (auditId, payload) => {
      const result = await d.requestJson(`/warehouse/process-audits/${auditId}/evidences`, {
        method: "POST",
        body: JSON.stringify(payload || {}),
      });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      return result.data.evidenceId;
    },
    removeProcessAuditEvidence: async (auditId, evidenceId) => {
      const result = await d.requestJson(`/warehouse/process-audits/${auditId}/evidences/${evidenceId}`, { method: "DELETE" });
      d.applyRemoteWarehouseState(result.data.state, d.setState, d.setLoginDirectory, d.skipNextSyncRef, d.setSyncStatus);
      return result.data.evidenceId;
    },
    Package: d.Package,
    PAGE_CUSTOM_BOARDS: d.PAGE_CUSTOM_BOARDS,
    PAGE_DASHBOARD: d.PAGE_DASHBOARD,
    PAGE_PROCESS_AUDITS: d.PAGE_PROCESS_AUDITS,
    PAGE_TRANSPORT: d.PAGE_TRANSPORT,
    page: d.page,
    pauseAnalysis: d.pauseAnalysis,
    Pause: d.Pause,
    PauseCircle: d.PauseCircle,
    Pencil: d.Pencil,
    permissionFileInputRef: d.permissionFileInputRef,
    permissionsFeedback: d.permissionsFeedback,
    PERMISSION_PRESETS: d.PERMISSION_PRESETS,
    PieChart: d.PieChart,
    Play: d.Play,
    Plus: d.Plus,
    hardResetDashboard: d.hardResetDashboard,
    isRootLead: d.isRootLead,
    canManageDashboardState: d.canManageDashboardState,
    canManageDashboardControls: d.canManageDashboardControls,
    canExportDashboardData: d.canExportDashboardData,
    isDemoMode: d.isDemoMode,
    activateDemoMode: d.activateDemoMode,
    deactivateDemoMode: d.deactivateDemoMode,
    pushAppToast: d.pushAppToast,
    requestJson: d.requestJson,
    ROLE_LEAD: d.ROLE_LEAD,
    ROLE_JR: d.ROLE_JR,
    RotateCcw: d.RotateCcw,
    Search: d.Search,
    securityEvents: d.securityEvents,
    securityEventsStatus: d.securityEventsStatus,
    selectedBoardActionPermissions: d.selectedBoardActionPermissions,
    selectedCustomBoard: d.selectedCustomBoard,
    selectedCustomBoardDisplay: d.selectedCustomBoardDisplay,
    selectedCustomBoardHistoryOptions: d.selectedCustomBoardHistoryOptions,
    selectedCustomBoardSnapshot: d.selectedCustomBoardSnapshot,
    selectedCustomBoardViewId: d.selectedCustomBoardViewId,
    selectedCustomBoardSections: d.selectedCustomBoardSections,
    selectedAreaSectionId: d.selectedAreaSectionId,
    selectedAreaSection: d.selectedAreaSection,
    canChangeSelectedBoardOperationalContext: d.canChangeSelectedBoardOperationalContext,
    selectedPermissionBoard: d.selectedPermissionBoard,
    setAdminTab: d.setAdminTab,
    setAuditFilters: d.setAuditFilters,
    setBoardRuntimeFeedback: d.setBoardRuntimeFeedback,
    setCustomBoardActionsMenuOpen: d.setCustomBoardActionsMenuOpen,
    setCustomBoardSearch: d.setCustomBoardSearch,
    setDashboardFilters: d.setDashboardFilters,
    setDashboardSectionsOpen: d.setDashboardSectionsOpen,
    setDeleteBoardId: d.setDeleteBoardId,
    setDeleteBoardRowState: d.setDeleteBoardRowState,
    setDeleteInventoryId: d.setDeleteInventoryId,
    setDeleteUserId: d.setDeleteUserId,
    transferLead: d.transferLead,
    transferLeadTargetId: d.transferLeadTargetId,
    setTransferLeadTargetId: d.setTransferLeadTargetId,
    setEditWeekId: d.setEditWeekId,
    setHistoryPauseActivityId: d.setHistoryPauseActivityId,
    setInventoryActionsMenuOpen: d.setInventoryActionsMenuOpen,
    setInventoryCleaningSite: d.setInventoryCleaningSite,
    setInventorySearch: d.setInventorySearch,
    setInventoryTab: d.setInventoryTab,
    setLoginDirectory: d.setLoginDirectory,
    setPage: d.setPage,
    setNavTransportSection: d.setNavTransportSection,
    setSelectedCustomBoardId: d.setSelectedCustomBoardId,
    setSelectedCustomBoardViewId: d.setSelectedCustomBoardViewId,
    selectedCustomBoardRowId: d.selectedCustomBoardRowId,
    setSelectedCustomBoardRowId: d.setSelectedCustomBoardRowId,
    pendingOpenIncidenciaId: d.pendingOpenIncidenciaId,
    setPendingOpenIncidenciaId: d.setPendingOpenIncidenciaId,
    pendingOpenTransportRecordId: d.pendingOpenTransportRecordId,
    setPendingOpenTransportRecordId: d.setPendingOpenTransportRecordId,
    setSelectedAreaSectionId: d.setSelectedAreaSectionId,
    updateBoardOperationalContext: d.updateBoardOperationalContext,
    setSelectedHistoryWeekId: d.setSelectedHistoryWeekId,
    setSelectedPermissionBoardId: d.setSelectedPermissionBoardId,
    setState: d.setState,
    setSyncStatus: d.setSyncStatus,
    setUserRoleFilter: d.setUserRoleFilter,
    setUserSearch: d.setUserSearch,
    setUsersViewTab: d.setUsersViewTab,
    Settings: d.Settings,
    skipNextSyncRef: d.skipNextSyncRef,
    softDeleteCatalog: d.softDeleteCatalog,
    Square: d.Square,
    state: d.state,
    StatTile: d.StatTile,
    STATUS_FINISHED: d.STATUS_FINISHED,
    STATUS_PAUSED: d.STATUS_PAUSED,
    STATUS_PENDING: d.STATUS_PENDING,
    STATUS_RUNNING: d.STATUS_RUNNING,
    StatusBadge: d.StatusBadge,
    togglePermissionRole: d.togglePermissionRole,
    toggleUserActive: d.toggleUserActive,
    Trash2: d.Trash2,
    updateBoardAssignment: d.updateBoardAssignment,
    updateBoardRowValue: d.updateBoardRowValue,
    updateBoardRowTimeOverride: d.updateBoardRowTimeOverride,
    updatePermissionEntry: d.updatePermissionEntry,
    Upload: d.Upload,
    userMap: d.userMap,
    usersByAreaGroups: d.usersByAreaGroups,
    isHistoricalCustomBoardView: d.isHistoricalCustomBoardView,
    setSelectedCustomBoardViewId: d.setSelectedCustomBoardViewId,
    usersByCreatorGroups: d.usersByCreatorGroups,
    usersCreatedByMap: d.usersCreatedByMap,
    usersViewTab: d.usersViewTab,
    menuPermissionSections: d.menuPermissionSections || [],
    permissionRegistryFlat: d.permissionRegistryFlat || [],
    permissionRegistryStats: d.permissionRegistryStats || { sections: 0, tabs: 0, subtabs: 0, actions: 0, totalRows: 0 },
    playerEditor: d.playerEditor || null,
    userRoleFilter: d.userRoleFilter,
    userSearch: d.userSearch,
    userStats: d.userStats,
    USER_ROLES: d.USER_ROLES,
    allRoles: d.allRoles,
    customRoles: d.state.customRoles || [],
    roleModalOpen: d.roleModalOpen,
    roleModalName: d.roleModalName,
    setRoleModalName: d.setRoleModalName,
    roleModalEditId: d.roleModalEditId,
    roleModalError: d.roleModalError,
    roleSaving: d.roleSaving,
    openCreateRoleModal: d.openCreateRoleModal,
    openEditRoleModal: d.openEditRoleModal,
    submitRoleModal: d.submitRoleModal,
    handleDeleteCustomRole: d.handleDeleteCustomRole,
    updateSystemOperationalSettings: d.updateSystemOperationalSettings,
    operationalWorkWeek: {},
    setRoleModalOpen: d.setRoleModalOpen,
    Users: d.Users,
    canDeleteControlBoardEntry: d.canDeleteControlBoardEntry,
    visibleControlBoards: d.visibleControlBoards,
    visibleUsers: d.visibleUsers,
    weeklyAreaCoverageRows: d.weeklyAreaCoverageRows,
    Zap: d.Zap,
  };
}
