/** Temas y layouts del dashboard operativo por sección de área (PanelIndicadores). */

const DEFAULT_THEME = {
  layout: "default",
  accent: "#0f4c5c",
  accentSoft: "rgba(15, 76, 92, 0.1)",
  accentBorder: "rgba(15, 76, 92, 0.22)",
  heroVariant: "split",
  eyebrow: "Vista por área",
  subtitle: "Métricas del periodo filtradas para esta área operativa.",
  executiveTitle: "Indicadores del periodo",
  executiveSubtitle: "Resumen y métricas por tablero en una sola vista.",
  zoneOrder: ["executive", "players", "trends", "causes", "alerts", "areas"],
  sections: ["executive", "areas", "players", "trends", "inventory", "merma", "causes", "alerts"],
  spotlightKeys: ["total", "completed", "open", "boards"],
};

const AREA_DASHBOARD_THEMES = {
  inventario: {
    layout: "inventory",
    accent: "#0f766e",
    accentSoft: "rgba(15, 118, 110, 0.12)",
    accentBorder: "rgba(15, 118, 110, 0.28)",
    heroVariant: "tiles",
    eyebrow: "Centro de inventario",
    subtitle: "Ritmo de piezas, tarimas, merma y desempeño por producto en el periodo.",
    executiveTitle: "Pulso de inventario",
    executiveSubtitle: "KPIs de movimiento, cierre y tableros de control de stock.",
    trendsTitle: "Movimiento, tarimas y merma",
    trendsSubtitle: "Evolución del flujo y leaderboards de producto y merma.",
    playersTitle: "Rendimiento por player",
    playersSubtitle: "Tiempos y carga por persona en inventario.",
    sections: ["executive", "trends", "inventory", "merma", "players", "causes", "alerts"],
    zoneOrder: ["executive", "trends", "players", "causes", "alerts"],
    spotlightKeys: ["total", "completed", "inventorySkus", "mermaRows"],
  },
  calidad: {
    layout: "quality",
    accent: "#7c3aed",
    accentSoft: "rgba(124, 58, 237, 0.1)",
    accentBorder: "rgba(124, 58, 237, 0.28)",
    heroVariant: "scorecard",
    eyebrow: "Control de calidad",
    subtitle: "Cumplimiento, desviaciones y concentración de hallazgos por proceso.",
    executiveTitle: "Indicadores de conformidad",
    executiveSubtitle: "SLA, cierres y desempeño por tablero de calidad.",
    trendsTitle: "Tendencia de conformidad",
    trendsSubtitle: "Evolución de cierres y tiempos en el periodo.",
    causesTitle: "Hallazgos y causas raíz",
    causesSubtitle: "Pareto e Ishikawa de desviaciones y pausas.",
    playersTitle: "Desempeño por inspector",
    playersSubtitle: "Carga y cumplimiento por player de calidad.",
    sections: ["executive", "causes", "players", "trends", "alerts"],
    zoneOrder: ["executive", "causes", "players", "trends", "alerts"],
    spotlightKeys: ["sla", "completed", "exceeded", "paused"],
  },
  mantenimiento: {
    layout: "maintenance",
    accent: "#ea580c",
    accentSoft: "rgba(234, 88, 12, 0.1)",
    accentBorder: "rgba(234, 88, 12, 0.3)",
    heroVariant: "pulse",
    eyebrow: "Mantenimiento y continuidad",
    subtitle: "Pausas, excesos de tiempo y carga por player en el periodo.",
    executiveTitle: "Estado operativo",
    executiveSubtitle: "Alertas de tiempo, pausas y avance por tablero.",
    alertsTitle: "Alertas de tiempo y pausas",
    alertsSubtitle: "Excesos de límite y causas de interrupción prioritarias.",
    causesTitle: "Pareto de interrupciones",
    causesSubtitle: "Causas que más tiempo consumen en mantenimiento.",
    playersTitle: "Carga por técnico",
    playersSubtitle: "Tiempos y pausas por player.",
    sections: ["executive", "alerts", "causes", "players", "trends"],
    zoneOrder: ["executive", "alerts", "causes", "players", "trends"],
    spotlightKeys: ["exceeded", "paused", "pauseCauses", "running"],
  },
  esto: {
    layout: "esto",
    accent: "#0369a1",
    accentSoft: "rgba(3, 105, 161, 0.1)",
    accentBorder: "rgba(3, 105, 161, 0.25)",
    heroVariant: "banner",
    eyebrow: "ESTO · ejecución",
    subtitle: "Seguimiento de registros, tiempos y distribución por área de trabajo.",
    executiveTitle: "Rendimiento ESTO",
    executiveSubtitle: "Volumen, cierres y tableros activos del periodo.",
    trendsTitle: "Evolución ESTO",
    trendsSubtitle: "Tendencia de registros y horas del periodo.",
    sections: ["executive", "trends", "players", "causes", "alerts"],
    zoneOrder: ["executive", "trends", "players", "causes", "alerts"],
    spotlightKeys: ["total", "completed", "areas", "hours"],
  },
  limpieza: {
    layout: "cleaning",
    accent: "#0284c7",
    accentSoft: "rgba(2, 132, 199, 0.1)",
    accentBorder: "rgba(2, 132, 199, 0.25)",
    heroVariant: "split",
    eyebrow: "Limpieza",
    subtitle: "Cobertura de actividades, cumplimiento y tiempos por equipo.",
    executiveTitle: "Indicadores de limpieza",
    executiveSubtitle: "Registros cerrados y desempeño por player.",
    playersTitle: "Equipo de limpieza",
    playersSubtitle: "Productividad y SLA por persona.",
    alertsSubtitle: "Excesos de límite y pausas. Los tiempos del catálogo de limpieza se ajustan solos tras 3 semanas de datos (ventana de 30 semanas), redondeados al alza en bloques de 5 min.",
    sections: ["executive", "players", "trends", "causes", "alerts"],
    zoneOrder: ["executive", "players", "trends", "alerts"],
    spotlightKeys: ["total", "completed", "sla", "players"],
  },
  regulatorio: {
    layout: "regulatory",
    accent: "#4f46e5",
    accentSoft: "rgba(79, 70, 229, 0.1)",
    accentBorder: "rgba(79, 70, 229, 0.28)",
    heroVariant: "scorecard",
    eyebrow: "Cumplimiento regulatorio",
    subtitle: "Trazabilidad de cierres, SLA y hallazgos del periodo.",
    executiveTitle: "Panel regulatorio",
    executiveSubtitle: "Métricas de conformidad y tableros auditables.",
    causesTitle: "No conformidades y causas",
    causesSubtitle: "Análisis Pareto e Ishikawa para auditoría.",
    sections: ["executive", "causes", "alerts", "players", "trends"],
    zoneOrder: ["executive", "causes", "alerts", "players", "trends"],
    spotlightKeys: ["sla", "completed", "exceeded", "total"],
  },
  "recepcion-pedidos": {
    layout: "reception",
    accent: "#b45309",
    accentSoft: "rgba(180, 83, 9, 0.1)",
    accentBorder: "rgba(180, 83, 9, 0.28)",
    heroVariant: "banner",
    eyebrow: "Recepción de pedidos",
    subtitle: "Flujo de entradas, tiempos de atención y carga por player.",
    executiveTitle: "Recepción en vivo",
    executiveSubtitle: "Volumen del periodo y eficiencia de cierre.",
    trendsTitle: "Flujo de recepción",
    trendsSubtitle: "Tendencia de entradas y tiempos de atención.",
    sections: ["executive", "trends", "players", "causes", "alerts"],
    zoneOrder: ["executive", "trends", "players", "alerts"],
    spotlightKeys: ["total", "running", "completed", "paused"],
  },
  operaciones: {
    layout: "operations",
    accent: "#334155",
    accentSoft: "rgba(51, 65, 85, 0.08)",
    accentBorder: "rgba(51, 65, 85, 0.22)",
    heroVariant: "split",
    eyebrow: "Operaciones",
    subtitle: "Balance de actividad, áreas y desempeño consolidado.",
    executiveTitle: "Torre de operaciones",
    executiveSubtitle: "KPIs transversales del periodo seleccionado.",
    sections: ["executive", "trends", "players", "causes", "alerts"],
    zoneOrder: ["executive", "trends", "players", "causes", "alerts"],
    spotlightKeys: ["total", "completed", "areas", "boards"],
  },
  transporte: {
    layout: "transport",
    accent: "#355f88",
    accentSoft: "rgba(53, 95, 136, 0.12)",
    accentBorder: "rgba(53, 95, 136, 0.28)",
    heroVariant: "banner",
    eyebrow: "Transporte",
    subtitle: "Resumen de tableros. Para salidas y consolidados usa el dashboard de Transporte.",
    executiveTitle: "Resumen transporte",
    executiveSubtitle: "Métricas de tableros vinculados al área.",
    trendsTitle: "Ritmo de salidas (tableros)",
    trendsSubtitle: "Tendencia operativa del periodo en tableros de transporte.",
    sections: ["executive", "trends", "players", "alerts"],
    zoneOrder: ["executive", "trends", "players", "alerts"],
    spotlightKeys: ["total", "completed", "running", "paused"],
  },
  "mejora-continua": {
    layout: "continuous",
    accent: "#6d28d9",
    accentSoft: "rgba(109, 40, 217, 0.1)",
    accentBorder: "rgba(109, 40, 217, 0.28)",
    heroVariant: "scorecard",
    eyebrow: "Mejora continua",
    subtitle: "Vista de tableros. El ciclo de auditorías vive en su módulo dedicado.",
    executiveTitle: "Indicadores de apoyo",
    executiveSubtitle: "Registros operativos del periodo en tableros.",
    sections: ["executive", "causes", "players", "trends", "alerts"],
    zoneOrder: ["executive", "causes", "players", "trends"],
    spotlightKeys: ["total", "completed", "exceeded", "paused"],
  },
  "mayoreo-comercio": {
    layout: "commerce",
    accent: "#db2777",
    accentSoft: "rgba(219, 39, 119, 0.1)",
    accentBorder: "rgba(219, 39, 119, 0.25)",
    heroVariant: "tiles",
    eyebrow: "Mayoreo / eCommerce",
    subtitle: "Desempeño comercial-operativo y tiempos por canal.",
    executiveTitle: "Pulso comercial",
    executiveSubtitle: "Cierres, pausas y carga por player.",
    playersTitle: "Equipo comercial",
    playersSubtitle: "Productividad por player en el periodo.",
    sections: ["executive", "players", "trends", "causes", "alerts"],
    zoneOrder: ["executive", "players", "trends", "alerts"],
    spotlightKeys: ["total", "completed", "players", "running"],
  },
  retail: {
    layout: "retail",
    accent: "#e11d48",
    accentSoft: "rgba(225, 29, 72, 0.1)",
    accentBorder: "rgba(225, 29, 72, 0.25)",
    heroVariant: "banner",
    eyebrow: "Retail",
    subtitle: "Actividad en piso, tiempos de atención y cumplimiento.",
    executiveTitle: "Retail operativo",
    executiveSubtitle: "Métricas del periodo por tablero y player.",
    sections: ["executive", "players", "trends", "causes", "alerts"],
    zoneOrder: ["executive", "players", "trends", "alerts"],
    spotlightKeys: ["total", "completed", "sla", "paused"],
  },
  fullfilment: {
    layout: "fulfillment",
    accent: "#0891b2",
    accentSoft: "rgba(8, 145, 178, 0.1)",
    accentBorder: "rgba(8, 145, 178, 0.25)",
    heroVariant: "tiles",
    eyebrow: "Fulfillment",
    subtitle: "Salidas, tiempos de preparación y productividad del periodo.",
    executiveTitle: "Fulfillment en curso",
    executiveSubtitle: "Registros, SLA y desempeño por equipo.",
    trendsTitle: "Preparación y salidas",
    trendsSubtitle: "Tendencia de volumen y tiempos de preparación.",
    sections: ["executive", "trends", "players", "causes", "alerts"],
    zoneOrder: ["executive", "trends", "players", "alerts"],
    spotlightKeys: ["total", "running", "completed", "hours"],
  },
  default: DEFAULT_THEME,
};

export function getAreaDashboardSections(theme) {
  return Array.isArray(theme?.sections) && theme.sections.length
    ? theme.sections
    : DEFAULT_THEME.sections;
}

const SPOTLIGHT_LABELS = {
  total: "Registros",
  completed: "Cerrados",
  open: "En curso",
  running: "Activos",
  paused: "Pausados",
  exceeded: "Fuera de SLA",
  boards: "Tableros",
  areas: "Áreas",
  players: "Players",
  sla: "SLA OK",
  hours: "Horas",
  inventorySkus: "SKUs medidos",
  mermaRows: "Filas merma",
  pauseCauses: "Causas pausa",
};

export function getAreaDashboardTheme(sectionId) {
  const key = String(sectionId || "").trim().toLowerCase();
  return { ...DEFAULT_THEME, ...(AREA_DASHBOARD_THEMES[key] || {}) };
}

export function getAreaDashboardZoneWrapClass(theme, zoneKey) {
  const order = theme.zoneOrder || DEFAULT_THEME.zoneOrder;
  const index = order.indexOf(zoneKey);
  const orderNum = index >= 0 ? index + 1 : 50;
  return `dashboard-zone-wrap dashboard-zone-wrap--${zoneKey} dashboard-zone-wrap--order-${orderNum}`;
}

export function buildAreaDashboardSpotlights(theme, metrics = {}, extras = {}) {
  const keys = theme.spotlightKeys || DEFAULT_THEME.spotlightKeys;
  const toneByKey = {
    exceeded: "danger",
    paused: "warning",
    mermaRows: "warning",
    pauseCauses: "warning",
    sla: "success",
    completed: "success",
    running: "info",
  };

  const values = {
    total: metrics.total ?? 0,
    completed: metrics.completed ?? 0,
    open: metrics.open ?? Math.max(0, (metrics.total ?? 0) - (metrics.completed ?? 0)),
    running: metrics.running ?? extras.running ?? 0,
    paused: metrics.paused ?? extras.paused ?? 0,
    exceeded: Array.isArray(metrics.exceeded) ? metrics.exceeded.length : (metrics.exceededCount ?? 0),
    boards: extras.boards ?? 0,
    areas: metrics.areaCount ?? 0,
    players: extras.players ?? 0,
    sla: extras.slaPercent != null ? `${extras.slaPercent}%` : "?",
    hours: extras.hours ?? "?",
    inventorySkus: extras.inventorySkus ?? 0,
    mermaRows: extras.mermaRows ?? 0,
    pauseCauses: extras.pauseCauses ?? 0,
  };

  return keys.map((key) => ({
    key,
    label: SPOTLIGHT_LABELS[key] || key,
    value: values[key] ?? 0,
    tone: toneByKey[key] || "neutral",
  }));
}
