import { BOARD_ACTIVITY_LIST_FIELD } from "./constantes";

/** Plantillas oficiales de sistema (4 fijas). Configuracion tomada de tableros operativos. */
export const EXTRA_SYSTEM_BOARD_TEMPLATES = [
{
    id: "actividades-reparaciones",
    name: "Actividades y Reparaciones",
    category: "Mantenimiento",
    description: "Plantilla oficial para registro de actividades y reparaciones de mantenimiento.",
    aliases: [],
    settings: {
      showWorkflow: true,
      showMetrics: true,
      showAssignee: true,
      showDates: true,
      showTotalTime: false,
      showEfficiency: false,
      useBoardCardsView: true,
      auxColumnsOrder: [
        "status",
        "time",
        "totalTime",
        "efficiency",
        "workflow",
        "assignee"
      ],
      columnOrder: [
        "fld-g8efcxwd",
        "fld-lhkmdna6",
        "fld-nm5sj2mv",
        "fld-tj4k85x5",
        "aux:time",
        "aux:workflow",
        "aux:assignee",
        "aux:status",
        "fld-sh2frbsw",
        "fld-zm1qr482",
        "fld-acvt6z27",
        "fld-4kee92v9",
        "fld-im7g4rru",
        "aux:totalTime",
        "aux:efficiency"
      ],
      operationalContextType: "none",
      operationalContextLabel: "",
      operationalContextOptions: [],
      operationalContextValue: "",
      cleaningCardLayout: {
        slotOrder: [
          "info",
          "player",
          "actions",
          "status",
          "timeline",
          "lotExpiry",
          "labelLab",
          "meta"
        ],
        hiddenSlots: [
          "lotExpiry",
          "labelLab"
        ],
        lineItemOrder: [
          "slot:info",
          "col:fld-sh2frbsw",
          "col:fld-im7g4rru",
          "col:fld-zm1qr482",
          "slot:player",
          "slot:actions",
          "slot:status",
          "col:fld-4kee92v9",
          "slot:timeline",
          "col:fld-acvt6z27"
        ]
      },
      cleaningCardSlotWidths: {
        info: 128,
        player: 127,
        timeline: 190
      }
    },
    columns: [
      {
        templateKey: "fld-g8efcxwd",
        label: "Fecha",
        type: "date",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "md",
        widthPx: 140,
        required: false,
        groupName: "Registro",
        groupColor: "#e8f4fc",
        layoutBlockRole: "date"
      },
      {
        templateKey: "fld-lhkmdna6",
        label: "Actividad/Reparación",
        type: "select",
        optionSource: "catalogByCategory",
        optionCatalogCategory: "Mantenimiento",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 190,
        required: true,
        groupName: "Captura",
        groupColor: "#dbeafe",
        layoutBlockRole: "activity"
      },
      {
        templateKey: "fld-nm5sj2mv",
        label: "Inicio",
        type: "time",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 130,
        required: false,
        groupName: "Tiempos",
        groupColor: "#fee2e2",
        layoutBlockRole: "start"
      },
      {
        templateKey: "fld-tj4k85x5",
        label: "Fin",
        type: "time",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: false,
        groupName: "Tiempos",
        groupColor: "#fee2e2",
        layoutBlockRole: "end"
      },
      {
        templateKey: "fld-sh2frbsw",
        label: "Reparación",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Registro",
        groupColor: "#e8f4fc"
      },
      {
        templateKey: "fld-zm1qr482",
        label: "Área",
        type: "select",
        optionSource: "manual",
        options: [
          "Pedidos",
          "Inventario",
          "Retail",
          "fullfilment",
          "RDP",
          "Oficinas C1",
          "Oficinas C2",
          "Oficinas C3",
          "Patio",
          "Caseta",
          "Baños C1",
          "Baños C2",
          "Baños C3",
          "General"
        ],
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 190,
        required: true,
        groupName: "Registro",
        groupColor: "#e8f4fc"
      },
      {
        templateKey: "fld-acvt6z27",
        label: "Observaciones",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: false,
        groupName: "Registro",
        groupColor: "#e8f4fc"
      },
      {
        templateKey: "fld-4kee92v9",
        label: "Antes/Despues",
        type: "evidenceGallery",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "md",
        required: false,
        groupName: "Evidencia",
        groupColor: "#f3e8ff"
      },
      {
        templateKey: "fld-im7g4rru",
        label: "Insumos a Utilizar",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "md",
        widthPx: 120,
        required: false,
        groupName: "Registro",
        groupColor: "#e8f4fc"
      }
    ]
  },
{
    id: "revision-tarimas",
    name: "Revisión de tarimas",
    category: "Revisión",
    description: "Plantilla oficial para revisión de tarimas con conteo, causales y evidencias.",
    aliases: [
      "revisión de tarimas",
      "revision de tarimas",
      "revisión de tarimas - fernando"
    ],
    settings: {
      showWorkflow: true,
      showMetrics: true,
      showAssignee: true,
      showDates: true,
      showTotalTime: false,
      showEfficiency: false,
      useBoardCardsView: true,
      auxColumnsOrder: [
        "status",
        "time",
        "totalTime",
        "efficiency",
        "workflow",
        "assignee"
      ],
      columnOrder: [
        "fld-85269fedd2d3",
        "fld-f40648205667",
        "aux:status",
        "aux:assignee",
        "aux:workflow",
        "fld-xmzxi524",
        "fld-t8a7tur8",
        "fld-4chtxlxo",
        "fld-pxaz78d9",
        "fld-gqgsp6kb",
        "fld-eaddedd70781",
        "aux:time",
        "fld-9ykaq0xx",
        "fld-ewq257wj",
        "fld-yi680qvq",
        "fld-wvs98frn",
        "fld-4c2p552d",
        "fld-urjjg6ip",
        "fld-c0f01fc518eb",
        "fld-fziuf4bl",
        "fld-w7yzaspm",
        "fld-40o4dszy",
        "aux:efficiency",
        "aux:totalTime"
      ],
      operationalContextType: "custom",
      operationalContextLabel: "Proceso",
      operationalContextOptions: [
        "Revisión"
      ],
      operationalContextValue: "Revisión",
      cleaningCardLayout: {
        slotOrder: [
          "info",
          "player",
          "actions",
          "status",
          "lotExpiry",
          "labelLab",
          "timeline",
          "meta"
        ],
        hiddenSlots: [],
        lineItemOrder: [
          "slot:info",
          "col:fld-ewq257wj",
          "col:fld-40o4dszy",
          "slot:player",
          "slot:actions",
          "slot:status",
          "slot:lotExpiry",
          "slot:labelLab",
          "col:fld-yi680qvq",
          "col:fld-9ykaq0xx",
          "col:fld-wvs98frn",
          "col:fld-w7yzaspm",
          "col:fld-4c2p552d",
          "col:fld-fziuf4bl",
          "slot:timeline",
          "col:fld-urjjg6ip",
          "col:fld-c0f01fc518eb"
        ]
      },
      cleaningCardSlotWidths: {
        info: 75,
        player: 146,
        timeline: 164,
        status: 81,
        lotExpiry: 110,
        labelLab: 84
      }
    },
    columns: [
      {
        templateKey: "fld-85269fedd2d3",
        label: "Tarima",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Identificador de la tarima revisada.",
        defaultValue: "",
        width: "sm",
        widthPx: 120,
        required: true,
        groupName: "Control",
        groupColor: "#ede9fe",
        layoutBlockRole: "activity"
      },
      {
        templateKey: "fld-f40648205667",
        label: "Fecha revisión",
        type: "date",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Fecha en la que se realizó la revisión de la tarima.",
        defaultValue: "",
        width: "sm",
        required: true,
        groupName: "Control",
        groupColor: "#ede9fe",
        layoutBlockRole: "date"
      },
      {
        templateKey: "fld-xmzxi524",
        label: "Lote",
        type: "inventoryProperty",
        optionSource: "manual",
        inventoryProperty: "lot",
        sourceFieldId: "fld-c33e8c18db00",
        formulaOperation: "add",
        helpText: "Lote tomado del inventario.",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Trazabilidad",
        groupColor: "#dcfce7",
        layoutBlockRole: "lot"
      },
      {
        templateKey: "fld-t8a7tur8",
        label: "Caducidad",
        type: "inventoryProperty",
        optionSource: "manual",
        inventoryProperty: "expiry",
        sourceFieldId: "fld-c33e8c18db00",
        formulaOperation: "add",
        helpText: "Caducidad tomada del inventario.",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Trazabilidad",
        groupColor: "#dcfce7",
        layoutBlockRole: "expiry"
      },
      {
        templateKey: "fld-4chtxlxo",
        label: "Etiqueta",
        type: "inventoryProperty",
        optionSource: "manual",
        inventoryProperty: "label",
        sourceFieldId: "fld-c33e8c18db00",
        formulaOperation: "add",
        helpText: "Etiqueta tomada del inventario.",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Trazabilidad",
        groupColor: "#dcfce7",
        layoutBlockRole: "labelTag"
      },
      {
        templateKey: "fld-pxaz78d9",
        label: "Laboratorio",
        type: "select",
        optionSource: "manual",
        options: [
          "GCE",
          "ZUMA",
          "PH&C"
        ],
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Laboratorio o marca del producto revisado.",
        defaultValue: "",
        width: "sm",
        widthPx: 190,
        required: true,
        groupName: "Trazabilidad",
        groupColor: "#dcfce7",
        layoutBlockRole: "laboratory"
      },
      {
        templateKey: "fld-gqgsp6kb",
        label: "Hora inicio",
        type: "time",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Hora de arranque de la revisión.",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Tiempos",
        groupColor: "#fee2e2",
        layoutBlockRole: "start"
      },
      {
        templateKey: "fld-eaddedd70781",
        label: "Hora fin",
        type: "time",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Hora de término de la revisión.",
        defaultValue: "",
        width: "sm",
        widthPx: 130,
        required: false,
        groupName: "Tiempos",
        groupColor: "#fee2e2",
        layoutBlockRole: "end"
      },
      {
        templateKey: "fld-9ykaq0xx",
        label: "Piezas por caja",
        type: "inventoryProperty",
        optionSource: "manual",
        inventoryProperty: "piecesPerBox",
        sourceFieldId: "fld-c33e8c18db00",
        formulaOperation: "add",
        helpText: "Piezas por caja tomadas del inventario.",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Conteo",
        groupColor: "#fef3c7"
      },
      {
        templateKey: "fld-ewq257wj",
        label: "Estación",
        type: "select",
        optionSource: "manual",
        options: [
          "Estación 1",
          "Estación 2",
          "Estación 3",
          "Estación 4",
          "Estación 5",
          "Estación 6"
        ],
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Control",
        groupColor: "#ede9fe"
      },
      {
        templateKey: "fld-yi680qvq",
        label: "Cajas Tarima",
        type: "number",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Cantidad de cajas revisadas.",
        defaultValue: 0,
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Conteo",
        groupColor: "#fef3c7"
      },
      {
        templateKey: "fld-wvs98frn",
        label: "Total piezas esperadas",
        type: "formula",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "multiply",
        formulaLeftFieldId: "fld-yi680qvq",
        formulaRightFieldId: "fld-9ykaq0xx",
        helpText: "Calcula el total esperado según cajas revisadas y piezas por caja.",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Conteo",
        groupColor: "#fef3c7"
      },
      {
        templateKey: "fld-4c2p552d",
        label: "Piezas Faltantes",
        type: "number",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        placeholder: "piezas por cajas incompletas",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Resultado",
        groupColor: "#fecaca"
      },
      {
        templateKey: "fld-urjjg6ip",
        label: "Total de PZ en buen estado",
        type: "formula",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "subtract",
        formulaLeftFieldId: "fld-wvs98frn",
        formulaRightFieldId: "fld-w7yzaspm",
        helpText: "Total de piezas contadas físicamente.",
        defaultValue: 0,
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Resultado",
        groupColor: "#fecaca"
      },
      {
        templateKey: "fld-c0f01fc518eb",
        label: "Observaciones",
        type: "textarea",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Observaciones generales de la revisión.",
        defaultValue: "",
        width: "lg",
        required: false,
        groupName: "Resultado",
        groupColor: "#fecaca"
      },
      {
        templateKey: "fld-fziuf4bl",
        label: "Causales",
        type: "multiSelectDetail",
        optionSource: "manual",
        options: [
          "Lote borroso",
          "Sin etiqueta",
          "Lote doble",
          "Sello roto/incompleto",
          "Bote dañado",
          "Lote diferente",
          "Sin lote"
        ],
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Selecciona una o varias causales y captura un dato adicional por cada una.",
        placeholder: "Cantidad o detalle",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: false,
        groupName: "Resultado",
        groupColor: "#fecaca"
      },
      {
        templateKey: "fld-w7yzaspm",
        label: "Piezas merma",
        type: "number",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Piezas identificadas como merma.",
        defaultValue: 0,
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Resultado",
        groupColor: "#fecaca"
      },
      {
        templateKey: "fld-40o4dszy",
        label: "Producto",
        type: "inventoryLookup",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Producto seleccionado desde inventario.",
        defaultValue: "",
        width: "lg",
        widthPx: 210,
        required: true,
        groupName: "Asignación",
        groupColor: "#e0f2fe"
      }
    ]
  },
{
    id: "actividades-limpieza",
    name: "Activiades de Limpieza",
    category: "Limpieza",
    description: "Plantilla oficial para control de actividades de limpieza.",
    aliases: [
      "activiades de limpieza",
      "actividades de limpieza",
      "control de actividades de limpieza"
    ],
    settings: {
      showWorkflow: true,
      showMetrics: true,
      showAssignee: true,
      showDates: true,
      showTotalTime: false,
      showEfficiency: false,
      useBoardCardsView: true,
      auxColumnsOrder: [
        "status",
        "time",
        "totalTime",
        "efficiency",
        "workflow",
        "assignee"
      ],
      columnOrder: [
        "fld-c0b3190cd0d7",
        "fld-3921067e921f",
        "aux:assignee",
        "fld-b06e4b52ee9b",
        "aux:workflow",
        "fld-725d39413206",
        "aux:status",
        "aux:time",
        "fld-uhfj530d",
        "fld-tnee5zho",
        "aux:totalTime",
        "aux:efficiency"
      ],
      operationalContextType: "cleaningSite",
      operationalContextLabel: "Sede de limpieza",
      operationalContextOptions: [
        "C1",
        "C2",
        "C3"
      ],
      operationalContextValue: "C3",
      cleaningCardLayout: {
        slotOrder: [
          "info",
          "actions",
          "player",
          "timeline",
          "status",
          "lotExpiry",
          "labelLab",
          "meta"
        ],
        hiddenSlots: [
          "lotExpiry",
          "labelLab"
        ],
        lineItemOrder: [
          "slot:info",
          "slot:actions",
          "slot:player",
          "slot:timeline",
          "slot:status",
          "col:fld-tnee5zho"
        ]
      },
      cleaningCardSlotWidths: {
        timeline: 198,
        status: 81,
        actions: 86,
        info: 163,
        player: 98
      }
    },
    columns: [
      {
        templateKey: "fld-c0b3190cd0d7",
        label: "Fecha",
        type: "date",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 140,
        required: false,
        groupName: "Registro",
        groupColor: "#e8f4fc",
        layoutBlockRole: "date"
      },
      {
        templateKey: "fld-3921067e921f",
        label: "Actividad",
        type: "select",
        optionSource: "catalogByCategory",
        optionCatalogCategory: "Limpieza",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 190,
        required: false,
        groupName: "Ejecución",
        groupColor: "#dbeafe",
        layoutBlockRole: "activity"
      },
      {
        templateKey: "fld-b06e4b52ee9b",
        label: "Inicio",
        type: "time",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: false,
        groupName: "Ejecución",
        groupColor: "#dbeafe",
        layoutBlockRole: "start"
      },
      {
        templateKey: "fld-725d39413206",
        label: "Fin",
        type: "time",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: false,
        groupName: "Ejecución",
        groupColor: "#dbeafe",
        layoutBlockRole: "end"
      },
      {
        templateKey: "fld-uhfj530d",
        label: "Se termino la actividad?",
        type: "select",
        optionSource: "manual",
        options: [
          "Si",
          "No"
        ],
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: true,
        groupName: "Ejecución",
        groupColor: "#dbeafe",
        layoutBlockRole: "finishGate"
      },
      {
        templateKey: "fld-tnee5zho",
        label: "Observaciones",
        type: "textarea",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        widthPx: 90,
        required: false,
        groupName: "Registro",
        groupColor: "#e8f4fc"
      }
    ]
  },
{
    id: "devoluciones-reacondicionado",
    name: "Devoluciones / Reacondicionado por tarima",
    category: "Revisión",
    description: "Plantilla oficial para flujo de escaneo continuo por tarima.",
    aliases: [
      "devoluciones / reacondicionado",
      "devoluciones y reacondicionado",
      "reacondicionado por tarima"
    ],
    settings: {
      showWorkflow: true,
      showMetrics: true,
      showAssignee: true,
      showDates: true,
      showTotalTime: true,
      showEfficiency: true,
      auxColumnsOrder: [
        "status",
        "time",
        "totalTime",
        "efficiency",
        "workflow",
        "assignee"
      ],
      columnOrder: [
        "fld-aa5yu0qg",
        "fld-lqci7vy2",
        "fld-p4y747x2",
        "fld-9v0ir966",
        "fld-creoh1kd",
        "fld-sesqse88",
        "fld-ecp2vp2y",
        "fld-uhdltbuw",
        "aux:status",
        "aux:time",
        "aux:totalTime",
        "aux:efficiency",
        "aux:workflow",
        "aux:assignee"
      ],
      operationalContextType: "custom",
      operationalContextLabel: "Proceso",
      operationalContextOptions: [
        "Devolucion",
        "Reacondicionado"
      ],
      operationalContextValue: "Devolucion"
    },
    columns: [
      {
        templateKey: "fld-aa5yu0qg",
        label: "Tarima",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        required: true,
        groupName: "Control",
        groupColor: "#ede9fe"
      },
      {
        templateKey: "fld-lqci7vy2",
        label: "Tipo de flujo",
        type: "select",
        optionSource: "manual",
        options: [
          "Devolucion",
          "Reacondicionado"
        ],
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        required: true,
        groupName: "Control",
        groupColor: "#ede9fe"
      },
      {
        templateKey: "fld-p4y747x2",
        label: "Producto",
        type: "inventoryLookup",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        helpText: "Producto desde inventario.",
        defaultValue: "",
        width: "lg",
        required: true,
        groupName: "Producto",
        groupColor: "#e0f2fe"
      },
      {
        templateKey: "fld-9v0ir966",
        label: "Lote",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        required: false,
        groupName: "Trazabilidad",
        groupColor: "#e8eff6"
      },
      {
        templateKey: "fld-creoh1kd",
        label: "Caducidad",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        required: false,
        groupName: "Trazabilidad",
        groupColor: "#e8eff6"
      },
      {
        templateKey: "fld-sesqse88",
        label: "Etiqueta",
        type: "text",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: "",
        width: "sm",
        required: false,
        groupName: "Trazabilidad",
        groupColor: "#e8eff6"
      },
      {
        templateKey: "fld-ecp2vp2y",
        label: "Piezas",
        type: "number",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: 0,
        width: "sm",
        required: false,
        groupName: "Conteo",
        groupColor: "#fef3c7"
      },
      {
        templateKey: "fld-uhdltbuw",
        label: "Meta de caja",
        type: "number",
        optionSource: "manual",
        inventoryProperty: "code",
        formulaOperation: "add",
        defaultValue: 50,
        width: "sm",
        required: false,
        groupName: "Conteo",
        groupColor: "#fef3c7"
      }
    ]
  }
];

export const PROTECTED_SYSTEM_BOARD_TEMPLATE_IDS = new Set([
  "actividades-reparaciones",
  "actividades-limpieza",
  "revision-tarimas",
  "devoluciones-reacondicionado",
]);
